import { db } from "../server/db";
import { products } from "../shared/schema";
import { eq } from "drizzle-orm";

const enhancedDescriptions: Record<string, string> = {
  // Gate Motors
  "Centurion D5 Evo Smart Gate Motor (No remotes included)": "Experience the award-winning Centurion D5 Evo Smart Gate Motor, engineered for residential and light commercial gates up to 500kg. This advanced sliding gate operator features SMART technology with wireless configuration via the MyCentsys app, delivering opening speeds of up to 24 meters per minute—making it the fastest in its class. Equipped with DOSS (Digital Obstacle Sensing System) for precision position control and ChronoGuard timer technology for automated scheduling. Includes comprehensive security features: tamper alarm, break-in alarm, and ambush alarm for enhanced property protection. The oil-bath lubrication system ensures maintenance-free operation, while the built-in battery backup system provides uninterrupted access during power outages. Features LCD controller with plug-and-play setup, 1500-button remote memory capacity, and South African-designed reliability backed by a 24-month warranty.",
  
  "Centurion D10 Smart Turbo Gate Motor (No remotes included)": "Introducing the Centurion D10 Smart Turbo—South Africa's premier industrial-grade sliding gate motor for heavy-duty applications up to 1000kg (1 ton). This 24V DC powerhouse delivers exceptional performance with turbo speed operation reaching up to 45 meters per minute, making it ideal for high-traffic commercial installations, estates, office parks, and warehouse facilities. The award-winning SMART technology enables complete wireless configuration and monitoring through the MyCentsys Pro mobile app, allowing you to set gate limits, speeds, auto-close timers, and manage up to 1500 remote control buttons. Features Hall Effect technology for accurate position control, universal SMART controller compatibility, and 24V battery backup system providing up to 35 cycles during power outages. The patented anti-theft cage design, integral vibration sensor, and advanced obstruction detection deliver enterprise-level security. With a daily cycle capacity of 750 operations and sleek, modern cover design, the D10 Turbo combines power, intelligence, and reliability for the most demanding automation requirements.",

  "Centurion VANTAGE 500 GATE MOTOR": "The Centurion Vantage 500 represents premium swing gate automation for large residential and commercial applications, designed to handle swing gates up to 500kg per leaf. This powerful underground motor system delivers smooth, quiet operation with adjustable force control, ensuring optimal performance for heavy ornamental gates, security installations, and estate entrances. Features comprehensive safety systems including obstacle detection, adjustable auto-close timers, and emergency manual release. The weather-resistant construction withstands harsh South African conditions, while the 24V DC motor provides reliable battery backup capability during load shedding. Compatible with Centurion's full range of remotes, intercoms, and access control systems, the Vantage 500 offers seamless integration into modern security infrastructure. Professional installation recommended for optimal alignment and performance.",

  // Remotes
  "Centurion Nova 1 Button Remote": "Secure your property with the Centurion Nova 1-Button Remote Control featuring automotive-grade Keeloq® code-hopping technology at 433MHz frequency. Unlike traditional fixed-code remotes vulnerable to cloning, this advanced transmitter generates a unique random code with every button press, providing the same encryption level used in modern car immobilizers. The sleek carbon-look design includes a rotating body for optimal button positioning and quick battery replacement. Perfect for single gate or garage control with reliable narrow-band receiver technology ensuring consistent signal reception even in signal-heavy environments. Each remote comes factory-programmed with a unique ID—no manual coding required. Compatible with all Centurion NOVA receivers and can be integrated with D5-Evo, D10, VECTOR2, and XTrac gate motor systems. Memory capacity supports up to 62 buttons on standard receivers or 125+ on SMART systems.",

  "Centurion Nova 4 Button Remote": "Take complete control of your automation systems with the Centurion Nova 4-Button Remote Control, featuring military-grade Keeloq® rolling code encryption at 433MHz for uncompromising security. This multi-channel transmitter allows independent control of up to four different systems—gate motors, garage doors, electric doors, and automated bollards—all from a single stylish device. The advanced code-hopping technology generates fresh encrypted signals with each activation, making signal interception and cloning impossible. The ergonomic carbon-look finish and rotating body design ensure comfortable operation and optimal antenna positioning for maximum range. Factory-coded with unique ID, compatible with Centurion's entire automation ecosystem including D5-Evo, D10, VECTOR2 swing gates, XTrac garage operators, and SECTOR traffic barriers. Receivers support up to 1500 button memory on SMART systems. Features quick battery replacement, weather-resistant construction, and reliable narrow-band RF technology for consistent performance in the South African climate.",

  "Gemini 1 Button Remote": "The Gemini 1-Button Remote Control delivers secure, reliable gate and garage automation with advanced code-hopping encryption technology. Designed for single-system control, this compact transmitter provides robust RF signal transmission with anti-jamming capabilities. Compatible with Gemini gate motors and receivers, featuring weatherproof construction for outdoor durability and long battery life for extended use. The simple one-button design is ideal for property owners seeking straightforward, dependable access control without unnecessary complexity.",

  "Gemini 4 Button Remote": "Maximize your automation control with the Gemini 4-Button Remote featuring multi-channel capability for up to four independent systems. This advanced transmitter employs code-hopping encryption to prevent unauthorized access and signal cloning. Control gate motors, garage doors, automated security gates, and additional access points from a single device. The compact, ergonomic design fits comfortably in your hand or pocket, while the weather-resistant housing ensures reliable performance in all South African weather conditions. Extended battery life and clear button labeling make operation simple and dependable for daily use.",

  "Sentry 1 Button C-Hop 433 NOVA Remote": "Experience advanced security with the Sentry 1-Button C-Hop 433MHz NOVA Remote, utilizing industry-standard code-hopping technology for maximum protection against signal interception. This professional-grade transmitter operates on the reliable 433MHz frequency band with NOVA compatibility, ensuring seamless integration with existing Centurion and compatible automation systems. The compact, robust design features weather-resistant construction, extended transmission range, and battery efficiency. Ideal for single gate or garage control in residential and light commercial applications where security and reliability are paramount.",

  "Sentry 3 Button C-Hop 433 NOVA Remote": "The Sentry 3-Button C-Hop 433MHz NOVA Remote combines versatility with robust security, featuring code-hopping encryption across three independent channels. Control multiple automation systems—including gates, garage doors, and security barriers—with advanced rolling code technology that prevents cloning and unauthorized access. Operating on the reliable 433MHz frequency with NOVA compatibility, this transmitter delivers consistent performance with extended range and minimal interference. The durable, pocket-sized design withstands daily use and harsh weather conditions, making it perfect for South African residential estates, commercial properties, and multi-unit developments.",

  "Sentry 4 Button C-Hop 433 NOVA Remote": "Unlock complete automation control with the Sentry 4-Button C-Hop 433MHz NOVA Remote, featuring four independently programmable channels with military-grade code-hopping security. This professional multi-system controller allows simultaneous management of gates, garages, automated doors, and access barriers—all protected by rolling code encryption that generates unique signals with every activation. The robust 433MHz transmission delivers reliable long-range performance, while NOVA compatibility ensures integration with Centurion and compatible automation infrastructure. Weather-resistant construction, ergonomic button layout, and extended battery life make this the ideal choice for property managers, estates, and security-conscious homeowners requiring comprehensive access control.",

  // Continue with CCTV products
  "Hilook 2MP Bullet Camera": "Achieve professional-grade surveillance with the HiLook 2MP Full HD Bullet Camera, delivering crisp 1920×1080p resolution for detailed monitoring of residential and commercial properties. This robust IP67-rated camera features advanced IR night vision technology with up to 30 meters range, capturing clear footage even in complete darkness with Smart IR adaptive illumination to prevent overexposure. The weatherproof design withstands South African weather extremes from -30°C to +60°C, perfect for outdoor perimeter security, parking areas, and building entrances. H.265+ video compression reduces bandwidth and storage requirements by up to 50% compared to H.264, while Wide Dynamic Range (WDR) technology ensures clarity in high-contrast lighting conditions. Supports both 12V DC and PoE (Power over Ethernet) for flexible single-cable installation. Compatible with HiLook and Hikvision NVR systems, offering remote viewing via HiLook Vision mobile app. Includes 2.8mm or 4mm lens options for customized field of view.",

  "4K Solar CCTV Camera": "Experience ultimate wireless security with this cutting-edge 4K Solar Powered Security Camera featuring WiFi connectivity and advanced night vision technology. The 8-megapixel ultra-high-definition sensor delivers four times the clarity of 1080p, capturing license plates, faces, and fine details with exceptional precision. Solar panel technology with high-efficiency photovoltaic cells ensures 24/7 operation without electrical wiring or frequent battery charging—perfect for remote locations, farms, construction sites, and perimeter monitoring. Built-in rechargeable battery provides up to 30 days standby during extended overcast periods. Advanced infrared LEDs illuminate up to 10-15 meters for full-color or black-and-white night vision modes. WiFi connectivity (2.4GHz) enables real-time mobile monitoring from anywhere via smartphone app with instant motion detection alerts, two-way audio communication, and cloud or microSD storage options (supports up to 128GB). IP66 weatherproof rating protects against dust, rain, and temperature extremes. PIR motion sensor reduces false alarms, while 355° pan and 90° tilt provide comprehensive coverage. Ideal for off-grid security applications where traditional power and cabling are impractical.",

  // Intercoms
  "Centurion G-Speak Ultra 4-button Intercom": "Transform your property access control with the Centurion G-Speak Ultra 4-Button GSM Intercom System—South Africa's leading wireless intercom solution that turns your mobile phone into a sophisticated access control handset. This 4G/LTE-enabled system eliminates traditional wired handsets, allowing visitors to call up to 2 phone numbers per button (8 total) from anywhere in the world. Configure and manage up to 100 active users or expand to 1500 users via the MyCentsys Remote app, with time-barring capabilities to restrict access during specific hours. The rugged aluminum fascia with backlit buttons ensures clear visibility day and night, while the IP-rated weatherproof enclosure withstands harsh outdoor conditions. Four configurable I/O channels enable integration with gate motors, electric fences, pool pumps, and security systems—controlling your entire property from your smartphone. Features include remote gate opening from anywhere, SMS/email notifications for events (gate open, power failure, tampering), custom message scheduling, and comprehensive administration via G-WEB online portal or mobile app. Power requirements: 10-30V DC with built-in 4G GSM module and both internal and external antenna options. Perfect for residential estates, commercial buildings, townhouse complexes, and multi-tenant properties requiring modern, scalable access control.",

  "Centurion G-Speak Ultra 2-button Intercom": "Simplify visitor access with the Centurion G-Speak Ultra 2-Button GSM Intercom, delivering professional wireless communication and remote gate control via 4G/LTE technology. This streamlined system calls up to 4 mobile numbers (2 per button), eliminating expensive handset installations and allowing property owners to answer from anywhere using their existing smartphones. Features weather-resistant aluminum construction with backlit buttons for night visibility, configurable time-barring for automated access restrictions, and I/O channels for gate motor integration. Remote management via G-WEB portal enables user administration, access scheduling, and system monitoring from any internet-connected device. Supports SMS, missed call, and email notifications for comprehensive property monitoring. Ideal for single and dual-residence applications, small offices, and agricultural properties requiring reliable, cost-effective access control without traditional intercom infrastructure.",

  // Batteries
  "12V 7AH Battery": "Power your critical security and automation systems with this premium 12V 7Ah Sealed Lead-Acid (SLA) battery, engineered for exceptional reliability in South African conditions. This maintenance-free, valve-regulated design delivers consistent voltage output for backup power supplies, alarm systems, gate motors (Centurion D5-Evo compatible), UPS devices, emergency lighting, and access control systems. Advanced AGM (Absorbent Glass Mat) technology provides superior charge acceptance, deep discharge recovery, and extended cycle life up to 3-5 years in standby applications. Leak-proof, spill-proof construction allows installation in any orientation, while low self-discharge rate (<3% per month) ensures readiness during extended storage. Operating temperature range: -15°C to +50°C. Rechargeable design with standard 12V chargers. Compact form factor (151mm x 65mm x 94mm) fits most gate motor and alarm panel compartments. Essential for load shedding protection and continuous operation of automated security systems.",

  "12V 8AH LITHIUM BATTERY": "Upgrade to next-generation power technology with this advanced 12V 8Ah Lithium Iron Phosphate (LiFePO4) battery, delivering superior performance and longevity compared to traditional lead-acid batteries. Featuring lightweight design (60% lighter than SLA equivalents), this lithium powerhouse provides 2000+ charge cycles—up to 4 times the lifespan of conventional batteries—making it the most cost-effective long-term solution for gate motors, solar systems, and security applications. Advanced Battery Management System (BMS) protects against overcharge, over-discharge, short circuit, and temperature extremes, ensuring safe, reliable operation in demanding South African conditions. Rapid charging capability (3-5 hours vs 8-12 hours for lead-acid) means faster recovery during frequent load shedding events. Zero maintenance required with flat discharge curve delivering consistent 12V power until fully depleted—no voltage sag like SLA batteries. Environmentally friendly with no toxic lead or acid. Compatible with Centurion gate motors, solar backup systems, portable equipment, and any 12V DC application. Operating range: -20°C to +60°C. Compact size, 10-year+ service life potential.",

  "Centurion Gate Motor Battery 12V 7AH CP4C2-28W": "Ensure optimal performance and compatibility with this genuine Centurion 12V 7.2Ah battery (CP4C2-28W), specifically engineered for Centurion gate motor systems including D5-Evo, D3-Evo, and VANTAGE models. This original equipment manufacturer (OEM) battery meets Centurion's exact specifications for voltage output, discharge characteristics, and physical dimensions, guaranteeing perfect fit and reliable backup power during load shedding and power outages. Factory-matched for optimal integration with Centurion's battery management and charging systems, preventing potential issues from third-party substitutes. Sealed lead-acid construction provides maintenance-free operation with proven reliability in South African climate extremes. Typical backup capacity: 10-40 gate cycles depending on motor model and gate weight. Recommended replacement interval: 2-3 years for consistent performance. Using genuine Centurion batteries maintains warranty compliance and ensures your gate automation system operates at peak efficiency.",

  // Continue with more products
  "Centurion D3/D5 EVO Smart & D6 Smart Base Plate": "Achieve professional-grade installation with this universal base plate compatible with Centurion D3-Evo, D5-Evo Smart, and D6 Smart gate motors. This precision-engineered mounting platform provides stable, level foundation for accurate motor alignment—critical for optimal performance, reduced wear, and quiet operation. Heavy-duty construction resists ground movement, settling, and vibration during gate cycles. Pre-drilled mounting holes ensure quick, secure installation with included fasteners. The robust design distributes motor weight evenly across the concrete foundation, preventing stress fractures and misalignment over time. Essential for professional installations requiring long-term reliability and compliance with manufacturer specifications. Corrosion-resistant finish withstands moisture and outdoor exposure.",

  "Centurion D5 Evo Main Cover Replacement": "Restore your Centurion D5-Evo gate motor's protection with this genuine replacement main cover, designed to shield sensitive electronics and mechanical components from South African weather extremes. This OEM cover provides identical fit and protection to the original, featuring UV-resistant ABS plastic construction that prevents sun degradation, water ingress from rain, and dust contamination. Precision-molded for perfect alignment with mounting points and ventilation requirements, ensuring proper motor cooling and electronic operation. The secure locking mechanism prevents unauthorized access while allowing easy maintenance access for authorized service. Maintains aesthetic appearance and professional installation standards. Using genuine Centurion parts ensures warranty compliance and optimal long-term protection for your gate automation investment.",

  "Centurion Gate Motor Door and Key": "Maintain secure access control to your Centurion gate motor's internal components with this replacement door and key set. Genuine Centurion part ensures perfect fit and secure closure, preventing unauthorized access to motor controls, battery compartment, and configuration settings. Robust construction withstands daily use and attempted tampering, while the precision-cut key provides smooth lock operation. Essential for property managers, security installations, and homeowners needing to restrict access to gate motor settings and emergency manual release controls. Compatible with multiple Centurion motor models—verify specific compatibility for your system.",

};

async function expandDescriptions() {
  try {
    console.log("Expanding product descriptions...");
    
    const allProducts = await db.select().from(products);
    console.log(`Found ${allProducts.length} products to process`);

    let updatedCount = 0;
    
    for (const product of allProducts) {
      const enhancedDesc = enhancedDescriptions[product.name];
      
      if (enhancedDesc && enhancedDesc !== product.description) {
        await db.update(products)
          .set({ description: enhancedDesc })
          .where(eq(products.id, product.id));
        
        console.log(`✓ Updated: ${product.name}`);
        updatedCount++;
      }
    }

    console.log(`\nCompleted! Updated ${updatedCount} product descriptions.`);
  } catch (error) {
    console.error("Error expanding descriptions:", error);
    throw error;
  }
}

expandDescriptions();
